#!/bin/bash
# openportwprocess, returns IP, COUNTRY, PORT#, PID, NAME
# Sorted on Country

for i in `~/HOMEWORK/Homework6/suspicious`
do
    PORT=`echo $i | awk -F: '{print $1}'`
    
    IP=`echo $i | awk -F: '{print $2}'`
    
    PID=`sudo lsof -i:$PORT | sed '1d' | head -1 |awk '{print $2}'`
    
    NAME=`sudo lsof -i:$PORT | sed '1d' | head -1 | awk '{print $1}'`
    
    COUNTRY=`curl -sSA "Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_3 like \
    Mac OS X; en-us)AppleWebKit/533.17.9 (KHTML, like Gecko) \
    Version/5.0.2 Mobile/8J2 Safari/6533.18.5" \
	 -H "Content-Type: text/html" https://whatismyipaddress.com/ip/$IP |
	grep Country | awk -F: '{print $2}' | awk -F">" '{print $3}' |
	awk -F"<" '{print $1}'`
	
	echo $IP $COUNTRY $PORT $PID $NAME | sort -k 2
done	
